### ISSUE TITLE
Hardcoded knot addresses

### ISSUE THREAD

**Issue by Skejven** [Knotx/knotx-fragments-handler#2]
Originally moved from https://github.com/Knotx/knotx-stack/pull/39#pullrequestreview-207231857
I know that we moved http repo connector to be a handler. Doing that Knot.x still supports the setup, where multiple repositories configuration is needed. In Knot.x 1.X it was possible due to defining new module in `modules` and assigning separate configuration to each http repo instance. Now it is possible because each route has its own repository and separate configuration for http handler. Maybe there should be an example or integration test for that case?

Another concern is that knots have now hardcoded addresses. I don't currently have the case when it might be required to run more than one instance of modules other than http repo, but maybe we should spend few more minutes on that. WDYT?

**Comment by tomaszmichalak** [comment]
This is fixed with #3 .
